apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-deployment
  namespace: disease-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: home-app
  template:
    metadata:
      labels:
        app: home-app
    spec:
      containers:
        - name: frontend
          image: blackmesa12/frontend:final
          envFrom:
            - configMapRef:
                name: env-configmap
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: home-service
  namespace: disease-app
spec:
  type: NodePort
  selector:
    app: home-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30000
