apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-deployment
  namespace: disease-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prediction-app
  template:
    metadata:
      labels:
        app: prediction-app
    spec:
      containers:
        - name: prediction
          image: blackmesa12/prediction:final
          envFrom:
            - configMapRef:
                name: env-configmap
          ports:
            - containerPort: 5001

---
apiVersion: v1
kind: Service
metadata:
  name: prediction-service
  namespace: disease-app
spec:
  selector:
    app: prediction-app
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  