apiVersion: apps/v1
kind: Deployment
metadata:
  name: results-deployment
  namespace: disease-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: results-app
  template:
    metadata:
      labels:
        app: results-app
    spec:
      containers:
        - name: results
          image: blackmesa12/results:final
          envFrom:
            - configMapRef:
                name: env-configmap
          ports:
            - containerPort: 5002

---
apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: disease-app
spec:
  selector:
    app: results-app
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
